/*
 * Kaia Mac
 * Large projext design and culminating project
 * 2018-2019
 */

/**
 *
 * @author kamac8665
 */
public class MathHelpCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MathHelpCalculator
     */
    public MathHelpCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        infoLabel1 = new javax.swing.JLabel();
        infoLabel5 = new javax.swing.JLabel();
        infoLabel9 = new javax.swing.JLabel();
        infoLabel10 = new javax.swing.JLabel();
        hypotInput1 = new javax.swing.JTextField();
        hypotInput2 = new javax.swing.JTextField();
        hypotButton = new javax.swing.JButton();
        hypotOutput = new javax.swing.JLabel();
        volumeInput1 = new javax.swing.JTextField();
        volumeInput2 = new javax.swing.JTextField();
        volumeButton = new javax.swing.JButton();
        infoLabel2 = new javax.swing.JLabel();
        volumeOutput = new javax.swing.JLabel();
        infoLabel6 = new javax.swing.JLabel();
        infoLabel11 = new javax.swing.JLabel();
        infoLabel12 = new javax.swing.JLabel();
        squaredInput = new javax.swing.JTextField();
        squaredButton = new javax.swing.JButton();
        infoLabel3 = new javax.swing.JLabel();
        squaredOutput = new javax.swing.JLabel();
        infoLabel7 = new javax.swing.JLabel();
        cubedButton = new javax.swing.JButton();
        infoLabel4 = new javax.swing.JLabel();
        cubedOutput = new javax.swing.JLabel();
        infoLabel8 = new javax.swing.JLabel();
        cubedInput = new javax.swing.JTextField();
        infoLabel13 = new javax.swing.JLabel();
        volumeInput3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        infoLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoLabel1.setText("Find the hypotenuse of a right angle triangle:");

        infoLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        infoLabel5.setText("Enter the opposite and adjacent sides of the triangle and then press \"Hypot\" to calculate the hypotenuse:");

        infoLabel9.setText("Opposite");

        infoLabel10.setText("Adjacent");

        hypotButton.setText("Hypot");
        hypotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hypotButtonActionPerformed(evt);
            }
        });

        hypotOutput.setText("---");

        volumeButton.setText("Volume");
        volumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeButtonActionPerformed(evt);
            }
        });

        infoLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoLabel2.setText("Find the volume of a rectangular prism:");

        volumeOutput.setText("---");

        infoLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        infoLabel6.setText("Enter the length, width, and height of the prism then press \"\"Volume to calculate the volume:");

        infoLabel11.setText("Length");

        infoLabel12.setText("Width");

        squaredButton.setText("squared");
        squaredButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squaredButtonActionPerformed(evt);
            }
        });

        infoLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoLabel3.setText("Find the value of a number squared:");

        squaredOutput.setText("---");

        infoLabel7.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        infoLabel7.setText("enter a value and press \"Squared\" to calculate that value squared:");

        cubedButton.setText("cubed");
        cubedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubedButtonActionPerformed(evt);
            }
        });

        infoLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infoLabel4.setText("Find the value of a number cubed:");

        cubedOutput.setText("---");

        infoLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        infoLabel8.setText("enter a value and press \"cubed\" to calculate the value cubed:");

        infoLabel13.setText("Height");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nextButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoLabel9)
                                    .addComponent(hypotInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(volumeInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoLabel11)
                                    .addComponent(squaredInput, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(infoLabel10)
                                            .addComponent(hypotInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 171, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(volumeInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(infoLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(infoLabel13)
                                            .addComponent(volumeInput3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(cubedInput, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hypotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(hypotOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(volumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(volumeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(squaredButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(squaredOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cubedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(cubedOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoLabel1)
                            .addComponent(infoLabel2)
                            .addComponent(infoLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoLabel5)
                                    .addComponent(infoLabel6)
                                    .addComponent(infoLabel7)
                                    .addComponent(infoLabel8)))
                            .addComponent(infoLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoLabel9)
                    .addComponent(infoLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hypotInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hypotInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hypotButton)
                    .addComponent(hypotOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoLabel11)
                            .addComponent(infoLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(volumeInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volumeInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volumeButton)
                            .addComponent(volumeOutput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(squaredInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(squaredButton)
                            .addComponent(squaredOutput))
                        .addGap(14, 14, 14)
                        .addComponent(infoLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(infoLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volumeInput3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cubedButton)
                    .addComponent(cubedInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cubedOutput))
                .addGap(18, 18, 18)
                .addComponent(nextButton)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        //when button is pressed, make this window terminate and make the next window visible.
        
        this.setVisible(false);
        MathHelpCalculatorPRT2 R = new MathHelpCalculatorPRT2();
        R.setVisible(true); 
    }//GEN-LAST:event_nextButtonActionPerformed

/**
* This method calculates the hypotenuse of a triangle and returns the value to the user
*/
    public static double hypotOfTri (double hypot,double opp,double adj){
        opp = opp * opp;
        adj = adj * adj;
        hypot = opp + adj;
        return Math.sqrt(hypot);
    }
    
    private void hypotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hypotButtonActionPerformed
        //Initializing variables
        
        double opp;
        double adj;
        double hypot;
        
        
        try{
            hypot = 0;
            opp = Double.parseDouble(hypotInput1.getText());
            adj = Double.parseDouble(hypotInput2.getText());

            hypotOutput.setText("" + hypotOfTri(hypot, opp, adj)); 
        }
        catch(NumberFormatException nfe){
            hypotOutput.setText("You must enter integers.");
            System.err.println("Exception: " + nfe);
        }
        
    }//GEN-LAST:event_hypotButtonActionPerformed

/**
* This method calculates the volume of a prism and returns the value to the user
*/
    public static double volumeOfPrism (double length,double width,double height,double volume){
        volume = length * width;
        volume = volume * height;
        return volume;
    }
    
    private void volumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeButtonActionPerformed
        //Initializing variables
        
        double length;
        double width;
        double height;
        double volume;
        
        try{
            width = Double.parseDouble(volumeInput1.getText());
            height = Double.parseDouble(volumeInput2.getText());
            length = Double.parseDouble(volumeInput3.getText());
            volume = 0;
            
            volumeOutput.setText("" + volumeOfPrism(volume, length, width, height)); 
        }
        catch(NumberFormatException nfe){
            volumeOutput.setText("You must enter integers.");
            System.err.println("Exception: " + nfe);
        }
        
    }//GEN-LAST:event_volumeButtonActionPerformed

/**
* This method calculates the value of a number squared and returns the value to the user
*/
    public static double squared (double squared){
        squared = squared * squared;
        return squared;
    }
    
    private void squaredButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squaredButtonActionPerformed
        //Initializing variables
        
        double squared;
        
        try{
            squared = Double.parseDouble(squaredInput.getText());
            
            squaredOutput.setText("" + squared(squared)); 
        }
        catch(NumberFormatException nfe){
            squaredOutput.setText("You must enter integers.");
            System.err.println("Exception: " + nfe);
        }
        
    }//GEN-LAST:event_squaredButtonActionPerformed

/**
* This method calculates the value of a number squared and returns the value to the user
*/
    public static double cubed (double cubed){
        cubed = cubed * cubed;
        return cubed;
    }    
    
    private void cubedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubedButtonActionPerformed
        //Initializing variables
        
        double cubed;
        
        try{
            cubed = Double.parseDouble(cubedInput.getText());
            
            cubedOutput.setText("" + cubed(cubed)); 
        }
        catch(NumberFormatException nfe){
            cubedOutput.setText("You must enter integers.");
            System.err.println("Exception: " + nfe);
        }
        
    }//GEN-LAST:event_cubedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathHelpCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathHelpCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathHelpCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathHelpCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathHelpCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cubedButton;
    private javax.swing.JTextField cubedInput;
    private javax.swing.JLabel cubedOutput;
    private javax.swing.JButton hypotButton;
    private javax.swing.JTextField hypotInput1;
    private javax.swing.JTextField hypotInput2;
    private javax.swing.JLabel hypotOutput;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel10;
    private javax.swing.JLabel infoLabel11;
    private javax.swing.JLabel infoLabel12;
    private javax.swing.JLabel infoLabel13;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JLabel infoLabel3;
    private javax.swing.JLabel infoLabel4;
    private javax.swing.JLabel infoLabel5;
    private javax.swing.JLabel infoLabel6;
    private javax.swing.JLabel infoLabel7;
    private javax.swing.JLabel infoLabel8;
    private javax.swing.JLabel infoLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton squaredButton;
    private javax.swing.JTextField squaredInput;
    private javax.swing.JLabel squaredOutput;
    private javax.swing.JButton volumeButton;
    private javax.swing.JTextField volumeInput1;
    private javax.swing.JTextField volumeInput2;
    private javax.swing.JTextField volumeInput3;
    private javax.swing.JLabel volumeOutput;
    // End of variables declaration//GEN-END:variables
}
