/*
 * Kaia Mac
 * Large Project/Culminating project ICS3U
 * 2018-2019
 */

/**
 *
 * @author kamac8665
 */
public class MathHelpCalculatorPRT2 extends javax.swing.JFrame {

    public MathHelpCalculatorPRT2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        infoTitle5 = new javax.swing.JLabel();
        infoLabelForTitle5 = new javax.swing.JLabel();
        userInputPercent = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        outputLabelFV = new javax.swing.JLabel();
        finishLabel = new javax.swing.JLabel();
        finishButton = new javax.swing.JButton();
        helpLabel1ForTitle5 = new javax.swing.JLabel();
        helpLabel2ForTitle5 = new javax.swing.JLabel();
        userInputR = new javax.swing.JTextField();
        helpLabel3ForTitle5 = new javax.swing.JLabel();
        userInputLength = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        infoTitle5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        infoTitle5.setText("Financing");

        infoLabelForTitle5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        infoLabelForTitle5.setText("    Input the following information and press enter. The program will output how much you will have:");

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        outputLabelFV.setText("---");

        finishLabel.setText("Press the \"Finish\" button to continue:");

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        helpLabel1ForTitle5.setText("how much you earn per year(%):");

        helpLabel2ForTitle5.setText("how much you deposit every year($):");

        helpLabel3ForTitle5.setText("how long you want to invest for(In years):");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabelForTitle5)
                    .addComponent(infoTitle5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userInputR, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helpLabel2ForTitle5)
                            .addComponent(helpLabel3ForTitle5)
                            .addComponent(userInputLength, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userInputPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(outputLabelFV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(helpLabel1ForTitle5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(infoTitle5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabelForTitle5)
                .addGap(3, 3, 3)
                .addComponent(helpLabel1ForTitle5)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userInputPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterButton)
                    .addComponent(outputLabelFV))
                .addGap(18, 18, 18)
                .addComponent(helpLabel2ForTitle5)
                .addGap(1, 1, 1)
                .addComponent(userInputR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(helpLabel3ForTitle5)
                .addGap(1, 1, 1)
                .addComponent(userInputLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishLabel)
                    .addComponent(finishButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        //when button is pressed, make this window terminate and make the next window visible.
        
        this.setVisible(false);
        FormLastPage r = new FormLastPage();
        r.setVisible(true);
    }//GEN-LAST:event_finishButtonActionPerformed

    public static double financing (double futureValue, double interestRate, double amountPerYear, double time, double percentage, double value){
        
        //formula to find the future value
        //FV = [R((1+i)^n - 1)] / i
        
        //convert into decimal number
        interestRate = interestRate / 100;
        
        percentage = 1 + interestRate;
        
        // calculate the value multiplied by itself time times.
        for (int q = 1; q <= time; q = q + 1)
            {
                value = percentage * percentage;
                q = q + 1;
            }
        
        value = value - 1;
        
        value = value * amountPerYear;
        
        futureValue = value / interestRate;
        
        //Rounding to the nearest hundredth
        futureValue = futureValue * 100;
        futureValue = Math.round(futureValue);
        futureValue = futureValue / 100;
        
        //return value.
        return futureValue;
    }
    
    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        
        //initializing variables.
        double interestRate;
        double time;
        double amountPerYear;
        double futureValue;
        double percentage;
        double value;
        
        try{
            //try converting the string to a double.
            interestRate = Double.parseDouble(userInputPercent.getText());
            time = Double.parseDouble(userInputLength.getText());
            amountPerYear = Double.parseDouble(userInputR.getText());

            futureValue = 0;
            percentage = 0;
            value = 0;
            // Output the value of the future value
            outputLabelFV.setText("$" + financing(futureValue, interestRate, amountPerYear, time, percentage, value));
        }
        //crash if converting does not work.
        catch (NumberFormatException nfe){
            
            outputLabelFV.setText("That is an invalid number.");
            System.out.println("Exception: " + nfe);
            
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathHelpCalculatorPRT2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathHelpCalculatorPRT2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathHelpCalculatorPRT2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathHelpCalculatorPRT2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathHelpCalculatorPRT2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel finishLabel;
    private javax.swing.JLabel helpLabel1ForTitle5;
    private javax.swing.JLabel helpLabel2ForTitle5;
    private javax.swing.JLabel helpLabel3ForTitle5;
    private javax.swing.JLabel infoLabelForTitle5;
    private javax.swing.JLabel infoTitle5;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel outputLabelFV;
    private javax.swing.JTextField userInputLength;
    private javax.swing.JTextField userInputPercent;
    private javax.swing.JTextField userInputR;
    // End of variables declaration//GEN-END:variables
}
